name: Info
main: to.joe.j2mc.info.J2MC_Info
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Information module
commands:
  rules:
    description: give me the rules.
    usage: /help
  reloadinfo:
    description: reloads data from config.yml
    usage: /reloadinfo
    permission: j2mc.info.reload
    permission-message: You are not senior staff
  worldguardhelp:
    description: gives some basic protection help
    usage: /wordguardhelp
    permission: j2mc.info.worldguard
    permission-message: Not functional on this server
  who:
    aliases: [playerlist]
    description: oh god player list
    usage: /who
permissions:
  j2mc.info.reload:
    descriptions: gives access to /reloadinfo
  j2mc.info.worldguard:
    description: Get access to the worldguard info
